name = "about-me"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
account_id = "your-account-id"
project_name = "about-me"
main = "workers-site/index.js"
zone_id = "your-zone-id"
