name = "about-me"
compatibility_date = "2025-03-11"

[site]
bucket = "./dist"

[build]
command = "npm run build"

[env.production]
account_id = "seu-account-id-aqui"
project_name = "about-me"
main = "workers-site/index.js"
zone_id = "seu-zone-id-aqui"
